
- name: Configure ISIS on IOS XR
  hosts: xr
  gather_facts: no

  tasks:
    - name: Configure ISIS CORE as level-2-only
      cisco.iosxr.iosxr_config:
        parents:
          - router isis CORE
        lines:
          - is-type level-2-only




